### PR TITLE
Adding ACS Variables

### PR DESCRIPTION
**Pull request by michellemho**
Added variables listed in issue.

https://github.com/CartoDB/bigmetadata/issues/187

### CODE REVIEW

**Comment by ethervoid** [comment]
I've merged master and fixed some conflicts, you create this branch but didn't merge the last master.

Now the tests are failing but seem to be related to your changes. I leave here the trace:

```
======================================================================
FAIL: tests.test_metadata.test_table_task(<class 'tasks.us.census.acs.ACSMetaWrapper'>, {'sample': '5yr', 'geography': 'state', 'year': '2015'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/bigmetadata/tests/test_metadata.py", line 34, in test_table_task
    runtask(task, superclasses=[TagsTask, ColumnsTask, TableTask])
  File "/bigmetadata/tests/util.py", line 78, in runtask
    runtask(dep, superclasses=superclasses)
  File "/bigmetadata/tests/util.py", line 78, in runtask
    runtask(dep, superclasses=superclasses)
  File "/bigmetadata/tests/util.py", line 79, in runtask
    assert dep.complete() is True
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
commit SegmentTags__99914b932b
commit Columns__99914b932b
--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logg
```

**Comment by ethervoid** [comment]
@javitonino @antoniocarlon I managed to fix the problem here. So this should be able to be merged and included in the new dump. I leave it here if you want to merge it. (I'm not here next monday)

**Comment by ethervoid** [comment]
We have a missing column that was not added:

- C24060001 Civilian employed population 16 years and Over

**Comment by michellemho** [comment]
The variable "Civilian employed Population 16 years and over" already exists in the DO under a different code and name:
http://cartodb.github.io/bigmetadata/united_states/employment.html#employed-population

**Comment by javitonino** [comment]
Data loaded by bumping versions and loading all timespans with:

```
make run-parallel -- us.census.acs ExtractAll --year 2015 --sample 5yr
make run-parallel -- us.census.acs ExtractAll --year 2010 --sample 5yr
make run-parallel -- us.census.acs ExtractAll --year 2015 --sample 1yr
make run-parallel -- us.census.acs ExtractAll --year 2014 --sample 1yr
make run-parallel -- us.census.acs ExtractAll --year 2010 --sample 1yr
```

**Pull request merged**
