### PR TITLE
Revert parallel execution for Luigi

### PR DESCRIPTION
**Pull request by ethervoid**
After some working with it, we're getting odd behaviour using the
parallel execution so is better to avoid it by now

### CODE REVIEW

**Comment by ethervoid** [comment]
What do you think @antoniocarlon ?

**Comment by juanignaciosl** [comment]
I must admit that I don't have enough information. What "odd behaviour" are we getting and what do we lose if we remove it?

**Comment by antoniocarlon** [comment]
In our experience parallel execution + our implementation of the SQLAlchemy models don't behave well together.
If you have found more issues with that I would avoid using it until we have time to take a more deep look into it.

**Comment by ethervoid** [comment]
@juanignaciosl, for example, Eurostat works in single worker execution but if you put it in parallel execution it starts messing with the DB sessions and fails.

We have plenty of cases about problems with SQL Sessions and until we don't cleanse/revamp the models part using parallel execution is not going to be an option

**Comment by juanignaciosl** [comment]
@ethervoid thanks! I understand that you're well aware of the problems, but readers of this PR (that doesn't have any linked issue) should also be informed in order to understand it 👍

**Comment by ethervoid** [comment]
More info #336

**Pull request merged**
