### PR TITLE
Comments on sg-7

### PR DESCRIPTION
**Pull request by talos**
@aspcanada Just did a full review of the metadata and tables.  Looks amazing.

I identified a few dozen metadata issues.  Most of them are minor renaming or restyling.  There are also a few unit questions, and columns that could probably be combined.  There are a few columns that appear to be repeated between the NHS columns and Census columns, too -- those should be combined, and might involve a little bit of mucking in the Survey code to make it pull the appropriate column.

Since the diff was so long and the file was new, instead I made FIXME comments that you should delete when you resolve the underlying condition.

### CODE REVIEW

**Comment by aspcanada** [comment]
@talos, please review this PR with my changes per identified FIXME comments

**Comment by talos** [comment]
Great.  Will take a look ASAP, later today I think.

**Comment by talos** [comment]
Also, I've fixed nasty CI issue that was making the tests fail intermittently for reasons unrelated to the code.  Checks failing on the PR indicator should now be meaningful.

**Comment by talos** [comment]
@aspcanada Double check that the columns task runs locally -- we've got a failure on CI that looks legit: https://travis-ci.org/CartoDB/bigmetadata/builds/165366084

**Pull request merged**
