### PR TITLE
Change Luigi version to 2.7.0

### PR DESCRIPTION
**Pull request by antoniocarlon**
Release notes: https://github.com/spotify/luigi/releases

Some minor changes on `import`:

 - `BooleanParameter` has been removed in versión `2.5.0` (previously deprecated). Using `BoolParameter` instead
 - `S3Target` is now on `luigi.contrib.s3` instead of `luigi.s3`

**Note:** I have tested the new Luigi version with a couple of existing tasks and everything seems to be working as expected

### CODE REVIEW

**Comment by javitonino** [comment]
Ok, this seems to work. @antoniocarlon can you upload the image now? We can then rerun the tests to have more confirmation that this works.

**Comment by antoniocarlon** [comment]
I have pushed the image

**Comment by javitonino** [comment]
Meeec 🔴 
`Failure: ImportError (cannot import name CentralPlannerScheduler) ... ERROR`

**Comment by javitonino** [comment]
After last minichange, this is green. Merging.

**Pull request merged**
